server:
  servlet:
    context-path: /gerencia/api

springdoc:
  swagger-ui:
    path: /public/swagger

#spring:
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5433/gerencia-pessoa
#    username: postgres
#    password: admin

